/**
 * This class is generated by jOOQ
 */
package at.hammer.jooq_generated.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Album extends org.jooq.impl.TableImpl<at.hammer.jooq_generated.tables.records.AlbumRecord> {

	private static final long serialVersionUID = -1371423463;

	/**
	 * The singleton instance of <code>chinook.album</code>
	 */
	public static final at.hammer.jooq_generated.tables.Album ALBUM = new at.hammer.jooq_generated.tables.Album();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<at.hammer.jooq_generated.tables.records.AlbumRecord> getRecordType() {
		return at.hammer.jooq_generated.tables.records.AlbumRecord.class;
	}

	/**
	 * The column <code>chinook.album.AlbumId</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.AlbumRecord, java.lang.Integer> ALBUMID = createField("AlbumId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>chinook.album.Title</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.AlbumRecord, java.lang.String> TITLE = createField("Title", org.jooq.impl.SQLDataType.VARCHAR.length(160).nullable(false), this);

	/**
	 * The column <code>chinook.album.ArtistId</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.AlbumRecord, java.lang.Integer> ARTISTID = createField("ArtistId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * Create a <code>chinook.album</code> table reference
	 */
	public Album() {
		super("album", at.hammer.jooq_generated.Chinook.CHINOOK);
	}

	/**
	 * Create an aliased <code>chinook.album</code> table reference
	 */
	public Album(java.lang.String alias) {
		super(alias, at.hammer.jooq_generated.Chinook.CHINOOK, at.hammer.jooq_generated.tables.Album.ALBUM);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<at.hammer.jooq_generated.tables.records.AlbumRecord, java.lang.Integer> getIdentity() {
		return at.hammer.jooq_generated.Keys.IDENTITY_ALBUM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<at.hammer.jooq_generated.tables.records.AlbumRecord> getPrimaryKey() {
		return at.hammer.jooq_generated.Keys.KEY_ALBUM_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<at.hammer.jooq_generated.tables.records.AlbumRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<at.hammer.jooq_generated.tables.records.AlbumRecord>>asList(at.hammer.jooq_generated.Keys.KEY_ALBUM_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<at.hammer.jooq_generated.tables.records.AlbumRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<at.hammer.jooq_generated.tables.records.AlbumRecord, ?>>asList(at.hammer.jooq_generated.Keys.FK_ALBUMARTISTID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public at.hammer.jooq_generated.tables.Album as(java.lang.String alias) {
		return new at.hammer.jooq_generated.tables.Album(alias);
	}
}
