/**
 * This class is generated by jOOQ
 */
package at.hammer.jooq_generated.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Employee extends org.jooq.impl.TableImpl<at.hammer.jooq_generated.tables.records.EmployeeRecord> {

	private static final long serialVersionUID = 1409058775;

	/**
	 * The singleton instance of <code>chinook.employee</code>
	 */
	public static final at.hammer.jooq_generated.tables.Employee EMPLOYEE = new at.hammer.jooq_generated.tables.Employee();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<at.hammer.jooq_generated.tables.records.EmployeeRecord> getRecordType() {
		return at.hammer.jooq_generated.tables.records.EmployeeRecord.class;
	}

	/**
	 * The column <code>chinook.employee.EmployeeId</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.EmployeeRecord, java.lang.Integer> EMPLOYEEID = createField("EmployeeId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>chinook.employee.LastName</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.EmployeeRecord, java.lang.String> LASTNAME = createField("LastName", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this);

	/**
	 * The column <code>chinook.employee.FirstName</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.EmployeeRecord, java.lang.String> FIRSTNAME = createField("FirstName", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this);

	/**
	 * The column <code>chinook.employee.Title</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.EmployeeRecord, java.lang.String> TITLE = createField("Title", org.jooq.impl.SQLDataType.VARCHAR.length(30), this);

	/**
	 * The column <code>chinook.employee.ReportsTo</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.EmployeeRecord, java.lang.Integer> REPORTSTO = createField("ReportsTo", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>chinook.employee.BirthDate</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.EmployeeRecord, java.sql.Timestamp> BIRTHDATE = createField("BirthDate", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>chinook.employee.HireDate</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.EmployeeRecord, java.sql.Timestamp> HIREDATE = createField("HireDate", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>chinook.employee.Address</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.EmployeeRecord, java.lang.String> ADDRESS = createField("Address", org.jooq.impl.SQLDataType.VARCHAR.length(70), this);

	/**
	 * The column <code>chinook.employee.City</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.EmployeeRecord, java.lang.String> CITY = createField("City", org.jooq.impl.SQLDataType.VARCHAR.length(40), this);

	/**
	 * The column <code>chinook.employee.State</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.EmployeeRecord, java.lang.String> STATE = createField("State", org.jooq.impl.SQLDataType.VARCHAR.length(40), this);

	/**
	 * The column <code>chinook.employee.Country</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.EmployeeRecord, java.lang.String> COUNTRY = createField("Country", org.jooq.impl.SQLDataType.VARCHAR.length(40), this);

	/**
	 * The column <code>chinook.employee.PostalCode</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.EmployeeRecord, java.lang.String> POSTALCODE = createField("PostalCode", org.jooq.impl.SQLDataType.VARCHAR.length(10), this);

	/**
	 * The column <code>chinook.employee.Phone</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.EmployeeRecord, java.lang.String> PHONE = createField("Phone", org.jooq.impl.SQLDataType.VARCHAR.length(24), this);

	/**
	 * The column <code>chinook.employee.Fax</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.EmployeeRecord, java.lang.String> FAX = createField("Fax", org.jooq.impl.SQLDataType.VARCHAR.length(24), this);

	/**
	 * The column <code>chinook.employee.Email</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.EmployeeRecord, java.lang.String> EMAIL = createField("Email", org.jooq.impl.SQLDataType.VARCHAR.length(60), this);

	/**
	 * Create a <code>chinook.employee</code> table reference
	 */
	public Employee() {
		super("employee", at.hammer.jooq_generated.Chinook.CHINOOK);
	}

	/**
	 * Create an aliased <code>chinook.employee</code> table reference
	 */
	public Employee(java.lang.String alias) {
		super(alias, at.hammer.jooq_generated.Chinook.CHINOOK, at.hammer.jooq_generated.tables.Employee.EMPLOYEE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<at.hammer.jooq_generated.tables.records.EmployeeRecord, java.lang.Integer> getIdentity() {
		return at.hammer.jooq_generated.Keys.IDENTITY_EMPLOYEE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<at.hammer.jooq_generated.tables.records.EmployeeRecord> getPrimaryKey() {
		return at.hammer.jooq_generated.Keys.KEY_EMPLOYEE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<at.hammer.jooq_generated.tables.records.EmployeeRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<at.hammer.jooq_generated.tables.records.EmployeeRecord>>asList(at.hammer.jooq_generated.Keys.KEY_EMPLOYEE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<at.hammer.jooq_generated.tables.records.EmployeeRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<at.hammer.jooq_generated.tables.records.EmployeeRecord, ?>>asList(at.hammer.jooq_generated.Keys.FK_EMPLOYEEREPORTSTO);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public at.hammer.jooq_generated.tables.Employee as(java.lang.String alias) {
		return new at.hammer.jooq_generated.tables.Employee(alias);
	}
}
