/**
 * This class is generated by jOOQ
 */
package at.hammer.jooq_generated.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Invoice extends org.jooq.impl.TableImpl<at.hammer.jooq_generated.tables.records.InvoiceRecord> {

	private static final long serialVersionUID = 1268112205;

	/**
	 * The singleton instance of <code>chinook.invoice</code>
	 */
	public static final at.hammer.jooq_generated.tables.Invoice INVOICE = new at.hammer.jooq_generated.tables.Invoice();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<at.hammer.jooq_generated.tables.records.InvoiceRecord> getRecordType() {
		return at.hammer.jooq_generated.tables.records.InvoiceRecord.class;
	}

	/**
	 * The column <code>chinook.invoice.InvoiceId</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.InvoiceRecord, java.lang.Integer> INVOICEID = createField("InvoiceId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>chinook.invoice.CustomerId</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.InvoiceRecord, java.lang.Integer> CUSTOMERID = createField("CustomerId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>chinook.invoice.InvoiceDate</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.InvoiceRecord, java.sql.Timestamp> INVOICEDATE = createField("InvoiceDate", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this);

	/**
	 * The column <code>chinook.invoice.BillingAddress</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.InvoiceRecord, java.lang.String> BILLINGADDRESS = createField("BillingAddress", org.jooq.impl.SQLDataType.VARCHAR.length(70), this);

	/**
	 * The column <code>chinook.invoice.BillingCity</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.InvoiceRecord, java.lang.String> BILLINGCITY = createField("BillingCity", org.jooq.impl.SQLDataType.VARCHAR.length(40), this);

	/**
	 * The column <code>chinook.invoice.BillingState</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.InvoiceRecord, java.lang.String> BILLINGSTATE = createField("BillingState", org.jooq.impl.SQLDataType.VARCHAR.length(40), this);

	/**
	 * The column <code>chinook.invoice.BillingCountry</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.InvoiceRecord, java.lang.String> BILLINGCOUNTRY = createField("BillingCountry", org.jooq.impl.SQLDataType.VARCHAR.length(40), this);

	/**
	 * The column <code>chinook.invoice.BillingPostalCode</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.InvoiceRecord, java.lang.String> BILLINGPOSTALCODE = createField("BillingPostalCode", org.jooq.impl.SQLDataType.VARCHAR.length(10), this);

	/**
	 * The column <code>chinook.invoice.Total</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.InvoiceRecord, java.math.BigDecimal> TOTAL = createField("Total", org.jooq.impl.SQLDataType.DECIMAL.precision(10, 2).nullable(false), this);

	/**
	 * Create a <code>chinook.invoice</code> table reference
	 */
	public Invoice() {
		super("invoice", at.hammer.jooq_generated.Chinook.CHINOOK);
	}

	/**
	 * Create an aliased <code>chinook.invoice</code> table reference
	 */
	public Invoice(java.lang.String alias) {
		super(alias, at.hammer.jooq_generated.Chinook.CHINOOK, at.hammer.jooq_generated.tables.Invoice.INVOICE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<at.hammer.jooq_generated.tables.records.InvoiceRecord, java.lang.Integer> getIdentity() {
		return at.hammer.jooq_generated.Keys.IDENTITY_INVOICE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<at.hammer.jooq_generated.tables.records.InvoiceRecord> getPrimaryKey() {
		return at.hammer.jooq_generated.Keys.KEY_INVOICE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<at.hammer.jooq_generated.tables.records.InvoiceRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<at.hammer.jooq_generated.tables.records.InvoiceRecord>>asList(at.hammer.jooq_generated.Keys.KEY_INVOICE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<at.hammer.jooq_generated.tables.records.InvoiceRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<at.hammer.jooq_generated.tables.records.InvoiceRecord, ?>>asList(at.hammer.jooq_generated.Keys.FK_INVOICECUSTOMERID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public at.hammer.jooq_generated.tables.Invoice as(java.lang.String alias) {
		return new at.hammer.jooq_generated.tables.Invoice(alias);
	}
}
