/**
 * This class is generated by jOOQ
 */
package at.hammer.jooq_generated.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mediatype extends org.jooq.impl.TableImpl<at.hammer.jooq_generated.tables.records.MediatypeRecord> {

	private static final long serialVersionUID = -1611882890;

	/**
	 * The singleton instance of <code>chinook.mediatype</code>
	 */
	public static final at.hammer.jooq_generated.tables.Mediatype MEDIATYPE = new at.hammer.jooq_generated.tables.Mediatype();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<at.hammer.jooq_generated.tables.records.MediatypeRecord> getRecordType() {
		return at.hammer.jooq_generated.tables.records.MediatypeRecord.class;
	}

	/**
	 * The column <code>chinook.mediatype.MediaTypeId</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.MediatypeRecord, java.lang.Integer> MEDIATYPEID = createField("MediaTypeId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>chinook.mediatype.Name</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.MediatypeRecord, java.lang.String> NAME = createField("Name", org.jooq.impl.SQLDataType.VARCHAR.length(120), this);

	/**
	 * Create a <code>chinook.mediatype</code> table reference
	 */
	public Mediatype() {
		super("mediatype", at.hammer.jooq_generated.Chinook.CHINOOK);
	}

	/**
	 * Create an aliased <code>chinook.mediatype</code> table reference
	 */
	public Mediatype(java.lang.String alias) {
		super(alias, at.hammer.jooq_generated.Chinook.CHINOOK, at.hammer.jooq_generated.tables.Mediatype.MEDIATYPE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<at.hammer.jooq_generated.tables.records.MediatypeRecord, java.lang.Integer> getIdentity() {
		return at.hammer.jooq_generated.Keys.IDENTITY_MEDIATYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<at.hammer.jooq_generated.tables.records.MediatypeRecord> getPrimaryKey() {
		return at.hammer.jooq_generated.Keys.KEY_MEDIATYPE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<at.hammer.jooq_generated.tables.records.MediatypeRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<at.hammer.jooq_generated.tables.records.MediatypeRecord>>asList(at.hammer.jooq_generated.Keys.KEY_MEDIATYPE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public at.hammer.jooq_generated.tables.Mediatype as(java.lang.String alias) {
		return new at.hammer.jooq_generated.tables.Mediatype(alias);
	}
}
