/**
 * This class is generated by jOOQ
 */
package at.hammer.jooq_generated.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Playlist extends org.jooq.impl.TableImpl<at.hammer.jooq_generated.tables.records.PlaylistRecord> {

	private static final long serialVersionUID = 2076402452;

	/**
	 * The singleton instance of <code>chinook.playlist</code>
	 */
	public static final at.hammer.jooq_generated.tables.Playlist PLAYLIST = new at.hammer.jooq_generated.tables.Playlist();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<at.hammer.jooq_generated.tables.records.PlaylistRecord> getRecordType() {
		return at.hammer.jooq_generated.tables.records.PlaylistRecord.class;
	}

	/**
	 * The column <code>chinook.playlist.PlaylistId</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.PlaylistRecord, java.lang.Integer> PLAYLISTID = createField("PlaylistId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>chinook.playlist.Name</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.PlaylistRecord, java.lang.String> NAME = createField("Name", org.jooq.impl.SQLDataType.VARCHAR.length(120), this);

	/**
	 * Create a <code>chinook.playlist</code> table reference
	 */
	public Playlist() {
		super("playlist", at.hammer.jooq_generated.Chinook.CHINOOK);
	}

	/**
	 * Create an aliased <code>chinook.playlist</code> table reference
	 */
	public Playlist(java.lang.String alias) {
		super(alias, at.hammer.jooq_generated.Chinook.CHINOOK, at.hammer.jooq_generated.tables.Playlist.PLAYLIST);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<at.hammer.jooq_generated.tables.records.PlaylistRecord, java.lang.Integer> getIdentity() {
		return at.hammer.jooq_generated.Keys.IDENTITY_PLAYLIST;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<at.hammer.jooq_generated.tables.records.PlaylistRecord> getPrimaryKey() {
		return at.hammer.jooq_generated.Keys.KEY_PLAYLIST_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<at.hammer.jooq_generated.tables.records.PlaylistRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<at.hammer.jooq_generated.tables.records.PlaylistRecord>>asList(at.hammer.jooq_generated.Keys.KEY_PLAYLIST_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public at.hammer.jooq_generated.tables.Playlist as(java.lang.String alias) {
		return new at.hammer.jooq_generated.tables.Playlist(alias);
	}
}
