/**
 * This class is generated by jOOQ
 */
package at.hammer.jooq_generated.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Playlisttrack extends org.jooq.impl.TableImpl<at.hammer.jooq_generated.tables.records.PlaylisttrackRecord> {

	private static final long serialVersionUID = 1285148696;

	/**
	 * The singleton instance of <code>chinook.playlisttrack</code>
	 */
	public static final at.hammer.jooq_generated.tables.Playlisttrack PLAYLISTTRACK = new at.hammer.jooq_generated.tables.Playlisttrack();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<at.hammer.jooq_generated.tables.records.PlaylisttrackRecord> getRecordType() {
		return at.hammer.jooq_generated.tables.records.PlaylisttrackRecord.class;
	}

	/**
	 * The column <code>chinook.playlisttrack.PlaylistId</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.PlaylisttrackRecord, java.lang.Integer> PLAYLISTID = createField("PlaylistId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>chinook.playlisttrack.TrackId</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.PlaylisttrackRecord, java.lang.Integer> TRACKID = createField("TrackId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * Create a <code>chinook.playlisttrack</code> table reference
	 */
	public Playlisttrack() {
		super("playlisttrack", at.hammer.jooq_generated.Chinook.CHINOOK);
	}

	/**
	 * Create an aliased <code>chinook.playlisttrack</code> table reference
	 */
	public Playlisttrack(java.lang.String alias) {
		super(alias, at.hammer.jooq_generated.Chinook.CHINOOK, at.hammer.jooq_generated.tables.Playlisttrack.PLAYLISTTRACK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<at.hammer.jooq_generated.tables.records.PlaylisttrackRecord> getPrimaryKey() {
		return at.hammer.jooq_generated.Keys.KEY_PLAYLISTTRACK_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<at.hammer.jooq_generated.tables.records.PlaylisttrackRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<at.hammer.jooq_generated.tables.records.PlaylisttrackRecord>>asList(at.hammer.jooq_generated.Keys.KEY_PLAYLISTTRACK_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<at.hammer.jooq_generated.tables.records.PlaylisttrackRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<at.hammer.jooq_generated.tables.records.PlaylisttrackRecord, ?>>asList(at.hammer.jooq_generated.Keys.FK_PLAYLISTTRACKPLAYLISTID, at.hammer.jooq_generated.Keys.FK_PLAYLISTTRACKTRACKID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public at.hammer.jooq_generated.tables.Playlisttrack as(java.lang.String alias) {
		return new at.hammer.jooq_generated.tables.Playlisttrack(alias);
	}
}
