/**
 * This class is generated by jOOQ
 */
package at.hammer.jooq_generated.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Track extends org.jooq.impl.TableImpl<at.hammer.jooq_generated.tables.records.TrackRecord> {

	private static final long serialVersionUID = 628278382;

	/**
	 * The singleton instance of <code>chinook.track</code>
	 */
	public static final at.hammer.jooq_generated.tables.Track TRACK = new at.hammer.jooq_generated.tables.Track();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<at.hammer.jooq_generated.tables.records.TrackRecord> getRecordType() {
		return at.hammer.jooq_generated.tables.records.TrackRecord.class;
	}

	/**
	 * The column <code>chinook.track.TrackId</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.TrackRecord, java.lang.Integer> TRACKID = createField("TrackId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>chinook.track.Name</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.TrackRecord, java.lang.String> NAME = createField("Name", org.jooq.impl.SQLDataType.VARCHAR.length(200).nullable(false), this);

	/**
	 * The column <code>chinook.track.AlbumId</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.TrackRecord, java.lang.Integer> ALBUMID = createField("AlbumId", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>chinook.track.MediaTypeId</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.TrackRecord, java.lang.Integer> MEDIATYPEID = createField("MediaTypeId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>chinook.track.GenreId</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.TrackRecord, java.lang.Integer> GENREID = createField("GenreId", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>chinook.track.Composer</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.TrackRecord, java.lang.String> COMPOSER = createField("Composer", org.jooq.impl.SQLDataType.VARCHAR.length(220), this);

	/**
	 * The column <code>chinook.track.Milliseconds</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.TrackRecord, java.lang.Integer> MILLISECONDS = createField("Milliseconds", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this);

	/**
	 * The column <code>chinook.track.Bytes</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.TrackRecord, java.lang.Integer> BYTES = createField("Bytes", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>chinook.track.UnitPrice</code>. 
	 */
	public final org.jooq.TableField<at.hammer.jooq_generated.tables.records.TrackRecord, java.math.BigDecimal> UNITPRICE = createField("UnitPrice", org.jooq.impl.SQLDataType.DECIMAL.precision(10, 2).nullable(false), this);

	/**
	 * Create a <code>chinook.track</code> table reference
	 */
	public Track() {
		super("track", at.hammer.jooq_generated.Chinook.CHINOOK);
	}

	/**
	 * Create an aliased <code>chinook.track</code> table reference
	 */
	public Track(java.lang.String alias) {
		super(alias, at.hammer.jooq_generated.Chinook.CHINOOK, at.hammer.jooq_generated.tables.Track.TRACK);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<at.hammer.jooq_generated.tables.records.TrackRecord, java.lang.Integer> getIdentity() {
		return at.hammer.jooq_generated.Keys.IDENTITY_TRACK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<at.hammer.jooq_generated.tables.records.TrackRecord> getPrimaryKey() {
		return at.hammer.jooq_generated.Keys.KEY_TRACK_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<at.hammer.jooq_generated.tables.records.TrackRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<at.hammer.jooq_generated.tables.records.TrackRecord>>asList(at.hammer.jooq_generated.Keys.KEY_TRACK_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<at.hammer.jooq_generated.tables.records.TrackRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<at.hammer.jooq_generated.tables.records.TrackRecord, ?>>asList(at.hammer.jooq_generated.Keys.FK_TRACKALBUMID, at.hammer.jooq_generated.Keys.FK_TRACKMEDIATYPEID, at.hammer.jooq_generated.Keys.FK_TRACKGENREID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public at.hammer.jooq_generated.tables.Track as(java.lang.String alias) {
		return new at.hammer.jooq_generated.tables.Track(alias);
	}
}
