/**
 * This class is generated by jOOQ
 */
package at.hammer.jooq_generated.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlbumRecord extends org.jooq.impl.UpdatableRecordImpl<at.hammer.jooq_generated.tables.records.AlbumRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = 793666838;

	/**
	 * Setter for <code>chinook.album.AlbumId</code>. 
	 */
	public void setAlbumid(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>chinook.album.AlbumId</code>. 
	 */
	public java.lang.Integer getAlbumid() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>chinook.album.Title</code>. 
	 */
	public void setTitle(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>chinook.album.Title</code>. 
	 */
	public java.lang.String getTitle() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>chinook.album.ArtistId</code>. 
	 */
	public void setArtistid(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>chinook.album.ArtistId</code>. 
	 */
	public java.lang.Integer getArtistid() {
		return (java.lang.Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return at.hammer.jooq_generated.tables.Album.ALBUM.ALBUMID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return at.hammer.jooq_generated.tables.Album.ALBUM.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return at.hammer.jooq_generated.tables.Album.ALBUM.ARTISTID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getAlbumid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getArtistid();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AlbumRecord
	 */
	public AlbumRecord() {
		super(at.hammer.jooq_generated.tables.Album.ALBUM);
	}

	/**
	 * Create a detached, initialised AlbumRecord
	 */
	public AlbumRecord(java.lang.Integer albumid, java.lang.String title, java.lang.Integer artistid) {
		super(at.hammer.jooq_generated.tables.Album.ALBUM);

		setValue(0, albumid);
		setValue(1, title);
		setValue(2, artistid);
	}
}
