/**
 * This class is generated by jOOQ
 */
package at.hammer.jooq_generated.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployeeRecord extends org.jooq.impl.UpdatableRecordImpl<at.hammer.jooq_generated.tables.records.EmployeeRecord> implements org.jooq.Record15<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 276193441;

	/**
	 * Setter for <code>chinook.employee.EmployeeId</code>. 
	 */
	public void setEmployeeid(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>chinook.employee.EmployeeId</code>. 
	 */
	public java.lang.Integer getEmployeeid() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>chinook.employee.LastName</code>. 
	 */
	public void setLastname(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>chinook.employee.LastName</code>. 
	 */
	public java.lang.String getLastname() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>chinook.employee.FirstName</code>. 
	 */
	public void setFirstname(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>chinook.employee.FirstName</code>. 
	 */
	public java.lang.String getFirstname() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>chinook.employee.Title</code>. 
	 */
	public void setTitle(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>chinook.employee.Title</code>. 
	 */
	public java.lang.String getTitle() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>chinook.employee.ReportsTo</code>. 
	 */
	public void setReportsto(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>chinook.employee.ReportsTo</code>. 
	 */
	public java.lang.Integer getReportsto() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>chinook.employee.BirthDate</code>. 
	 */
	public void setBirthdate(java.sql.Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>chinook.employee.BirthDate</code>. 
	 */
	public java.sql.Timestamp getBirthdate() {
		return (java.sql.Timestamp) getValue(5);
	}

	/**
	 * Setter for <code>chinook.employee.HireDate</code>. 
	 */
	public void setHiredate(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>chinook.employee.HireDate</code>. 
	 */
	public java.sql.Timestamp getHiredate() {
		return (java.sql.Timestamp) getValue(6);
	}

	/**
	 * Setter for <code>chinook.employee.Address</code>. 
	 */
	public void setAddress(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>chinook.employee.Address</code>. 
	 */
	public java.lang.String getAddress() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>chinook.employee.City</code>. 
	 */
	public void setCity(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>chinook.employee.City</code>. 
	 */
	public java.lang.String getCity() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>chinook.employee.State</code>. 
	 */
	public void setState(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>chinook.employee.State</code>. 
	 */
	public java.lang.String getState() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>chinook.employee.Country</code>. 
	 */
	public void setCountry(java.lang.String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>chinook.employee.Country</code>. 
	 */
	public java.lang.String getCountry() {
		return (java.lang.String) getValue(10);
	}

	/**
	 * Setter for <code>chinook.employee.PostalCode</code>. 
	 */
	public void setPostalcode(java.lang.String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>chinook.employee.PostalCode</code>. 
	 */
	public java.lang.String getPostalcode() {
		return (java.lang.String) getValue(11);
	}

	/**
	 * Setter for <code>chinook.employee.Phone</code>. 
	 */
	public void setPhone(java.lang.String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>chinook.employee.Phone</code>. 
	 */
	public java.lang.String getPhone() {
		return (java.lang.String) getValue(12);
	}

	/**
	 * Setter for <code>chinook.employee.Fax</code>. 
	 */
	public void setFax(java.lang.String value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>chinook.employee.Fax</code>. 
	 */
	public java.lang.String getFax() {
		return (java.lang.String) getValue(13);
	}

	/**
	 * Setter for <code>chinook.employee.Email</code>. 
	 */
	public void setEmail(java.lang.String value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>chinook.employee.Email</code>. 
	 */
	public java.lang.String getEmail() {
		return (java.lang.String) getValue(14);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record15 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row15<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row15) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row15<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.sql.Timestamp, java.sql.Timestamp, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row15) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return at.hammer.jooq_generated.tables.Employee.EMPLOYEE.EMPLOYEEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return at.hammer.jooq_generated.tables.Employee.EMPLOYEE.LASTNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return at.hammer.jooq_generated.tables.Employee.EMPLOYEE.FIRSTNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return at.hammer.jooq_generated.tables.Employee.EMPLOYEE.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return at.hammer.jooq_generated.tables.Employee.EMPLOYEE.REPORTSTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field6() {
		return at.hammer.jooq_generated.tables.Employee.EMPLOYEE.BIRTHDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return at.hammer.jooq_generated.tables.Employee.EMPLOYEE.HIREDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return at.hammer.jooq_generated.tables.Employee.EMPLOYEE.ADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return at.hammer.jooq_generated.tables.Employee.EMPLOYEE.CITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return at.hammer.jooq_generated.tables.Employee.EMPLOYEE.STATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field11() {
		return at.hammer.jooq_generated.tables.Employee.EMPLOYEE.COUNTRY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field12() {
		return at.hammer.jooq_generated.tables.Employee.EMPLOYEE.POSTALCODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field13() {
		return at.hammer.jooq_generated.tables.Employee.EMPLOYEE.PHONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field14() {
		return at.hammer.jooq_generated.tables.Employee.EMPLOYEE.FAX;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field15() {
		return at.hammer.jooq_generated.tables.Employee.EMPLOYEE.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getEmployeeid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getLastname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getFirstname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getReportsto();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value6() {
		return getBirthdate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getHiredate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getAddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getCity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getState();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value11() {
		return getCountry();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value12() {
		return getPostalcode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value13() {
		return getPhone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value14() {
		return getFax();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value15() {
		return getEmail();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EmployeeRecord
	 */
	public EmployeeRecord() {
		super(at.hammer.jooq_generated.tables.Employee.EMPLOYEE);
	}

	/**
	 * Create a detached, initialised EmployeeRecord
	 */
	public EmployeeRecord(java.lang.Integer employeeid, java.lang.String lastname, java.lang.String firstname, java.lang.String title, java.lang.Integer reportsto, java.sql.Timestamp birthdate, java.sql.Timestamp hiredate, java.lang.String address, java.lang.String city, java.lang.String state, java.lang.String country, java.lang.String postalcode, java.lang.String phone, java.lang.String fax, java.lang.String email) {
		super(at.hammer.jooq_generated.tables.Employee.EMPLOYEE);

		setValue(0, employeeid);
		setValue(1, lastname);
		setValue(2, firstname);
		setValue(3, title);
		setValue(4, reportsto);
		setValue(5, birthdate);
		setValue(6, hiredate);
		setValue(7, address);
		setValue(8, city);
		setValue(9, state);
		setValue(10, country);
		setValue(11, postalcode);
		setValue(12, phone);
		setValue(13, fax);
		setValue(14, email);
	}
}
