/**
 * This class is generated by jOOQ
 */
package at.hammer.jooq_generated.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InvoiceRecord extends org.jooq.impl.UpdatableRecordImpl<at.hammer.jooq_generated.tables.records.InvoiceRecord> implements org.jooq.Record9<java.lang.Integer, java.lang.Integer, java.sql.Timestamp, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.math.BigDecimal> {

	private static final long serialVersionUID = 1938403698;

	/**
	 * Setter for <code>chinook.invoice.InvoiceId</code>. 
	 */
	public void setInvoiceid(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>chinook.invoice.InvoiceId</code>. 
	 */
	public java.lang.Integer getInvoiceid() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>chinook.invoice.CustomerId</code>. 
	 */
	public void setCustomerid(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>chinook.invoice.CustomerId</code>. 
	 */
	public java.lang.Integer getCustomerid() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>chinook.invoice.InvoiceDate</code>. 
	 */
	public void setInvoicedate(java.sql.Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>chinook.invoice.InvoiceDate</code>. 
	 */
	public java.sql.Timestamp getInvoicedate() {
		return (java.sql.Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>chinook.invoice.BillingAddress</code>. 
	 */
	public void setBillingaddress(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>chinook.invoice.BillingAddress</code>. 
	 */
	public java.lang.String getBillingaddress() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>chinook.invoice.BillingCity</code>. 
	 */
	public void setBillingcity(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>chinook.invoice.BillingCity</code>. 
	 */
	public java.lang.String getBillingcity() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>chinook.invoice.BillingState</code>. 
	 */
	public void setBillingstate(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>chinook.invoice.BillingState</code>. 
	 */
	public java.lang.String getBillingstate() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>chinook.invoice.BillingCountry</code>. 
	 */
	public void setBillingcountry(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>chinook.invoice.BillingCountry</code>. 
	 */
	public java.lang.String getBillingcountry() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>chinook.invoice.BillingPostalCode</code>. 
	 */
	public void setBillingpostalcode(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>chinook.invoice.BillingPostalCode</code>. 
	 */
	public java.lang.String getBillingpostalcode() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>chinook.invoice.Total</code>. 
	 */
	public void setTotal(java.math.BigDecimal value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>chinook.invoice.Total</code>. 
	 */
	public java.math.BigDecimal getTotal() {
		return (java.math.BigDecimal) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.Integer, java.sql.Timestamp, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.math.BigDecimal> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.Integer, java.sql.Timestamp, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.math.BigDecimal> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return at.hammer.jooq_generated.tables.Invoice.INVOICE.INVOICEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return at.hammer.jooq_generated.tables.Invoice.INVOICE.CUSTOMERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field3() {
		return at.hammer.jooq_generated.tables.Invoice.INVOICE.INVOICEDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return at.hammer.jooq_generated.tables.Invoice.INVOICE.BILLINGADDRESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return at.hammer.jooq_generated.tables.Invoice.INVOICE.BILLINGCITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return at.hammer.jooq_generated.tables.Invoice.INVOICE.BILLINGSTATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return at.hammer.jooq_generated.tables.Invoice.INVOICE.BILLINGCOUNTRY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return at.hammer.jooq_generated.tables.Invoice.INVOICE.BILLINGPOSTALCODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigDecimal> field9() {
		return at.hammer.jooq_generated.tables.Invoice.INVOICE.TOTAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getInvoiceid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getCustomerid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value3() {
		return getInvoicedate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getBillingaddress();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getBillingcity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getBillingstate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getBillingcountry();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getBillingpostalcode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigDecimal value9() {
		return getTotal();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached InvoiceRecord
	 */
	public InvoiceRecord() {
		super(at.hammer.jooq_generated.tables.Invoice.INVOICE);
	}

	/**
	 * Create a detached, initialised InvoiceRecord
	 */
	public InvoiceRecord(java.lang.Integer invoiceid, java.lang.Integer customerid, java.sql.Timestamp invoicedate, java.lang.String billingaddress, java.lang.String billingcity, java.lang.String billingstate, java.lang.String billingcountry, java.lang.String billingpostalcode, java.math.BigDecimal total) {
		super(at.hammer.jooq_generated.tables.Invoice.INVOICE);

		setValue(0, invoiceid);
		setValue(1, customerid);
		setValue(2, invoicedate);
		setValue(3, billingaddress);
		setValue(4, billingcity);
		setValue(5, billingstate);
		setValue(6, billingcountry);
		setValue(7, billingpostalcode);
		setValue(8, total);
	}
}
