/**
 * This class is generated by jOOQ
 */
package at.hammer.jooq_generated;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Chinook extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -412663694;

	/**
	 * The singleton instance of <code>chinook</code>
	 */
	public static final Chinook CHINOOK = new Chinook();

	/**
	 * No further instances allowed
	 */
	private Chinook() {
		super("chinook");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			at.hammer.jooq_generated.tables.Album.ALBUM,
			at.hammer.jooq_generated.tables.Artist.ARTIST,
			at.hammer.jooq_generated.tables.Customer.CUSTOMER,
			at.hammer.jooq_generated.tables.Employee.EMPLOYEE,
			at.hammer.jooq_generated.tables.Genre.GENRE,
			at.hammer.jooq_generated.tables.Invoice.INVOICE,
			at.hammer.jooq_generated.tables.Invoiceline.INVOICELINE,
			at.hammer.jooq_generated.tables.Mediatype.MEDIATYPE,
			at.hammer.jooq_generated.tables.Playlist.PLAYLIST,
			at.hammer.jooq_generated.tables.Playlisttrack.PLAYLISTTRACK,
			at.hammer.jooq_generated.tables.Track.TRACK);
	}
}
