/**
 * This class is generated by jOOQ
 */
package at.hammer.jooq_generated;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in chinook
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.2.0" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table chinook.album
	 */
	public static final at.hammer.jooq_generated.tables.Album ALBUM = at.hammer.jooq_generated.tables.Album.ALBUM;

	/**
	 * The table chinook.artist
	 */
	public static final at.hammer.jooq_generated.tables.Artist ARTIST = at.hammer.jooq_generated.tables.Artist.ARTIST;

	/**
	 * The table chinook.customer
	 */
	public static final at.hammer.jooq_generated.tables.Customer CUSTOMER = at.hammer.jooq_generated.tables.Customer.CUSTOMER;

	/**
	 * The table chinook.employee
	 */
	public static final at.hammer.jooq_generated.tables.Employee EMPLOYEE = at.hammer.jooq_generated.tables.Employee.EMPLOYEE;

	/**
	 * The table chinook.genre
	 */
	public static final at.hammer.jooq_generated.tables.Genre GENRE = at.hammer.jooq_generated.tables.Genre.GENRE;

	/**
	 * The table chinook.invoice
	 */
	public static final at.hammer.jooq_generated.tables.Invoice INVOICE = at.hammer.jooq_generated.tables.Invoice.INVOICE;

	/**
	 * The table chinook.invoiceline
	 */
	public static final at.hammer.jooq_generated.tables.Invoiceline INVOICELINE = at.hammer.jooq_generated.tables.Invoiceline.INVOICELINE;

	/**
	 * The table chinook.mediatype
	 */
	public static final at.hammer.jooq_generated.tables.Mediatype MEDIATYPE = at.hammer.jooq_generated.tables.Mediatype.MEDIATYPE;

	/**
	 * The table chinook.playlist
	 */
	public static final at.hammer.jooq_generated.tables.Playlist PLAYLIST = at.hammer.jooq_generated.tables.Playlist.PLAYLIST;

	/**
	 * The table chinook.playlisttrack
	 */
	public static final at.hammer.jooq_generated.tables.Playlisttrack PLAYLISTTRACK = at.hammer.jooq_generated.tables.Playlisttrack.PLAYLISTTRACK;

	/**
	 * The table chinook.track
	 */
	public static final at.hammer.jooq_generated.tables.Track TRACK = at.hammer.jooq_generated.tables.Track.TRACK;
}
